
var MANPAGES = {
    "auth": "Will prompt for credentials : user name, remote password (used to secure the database access), local password (used to encrypt the local content)<br>" +
            "If this command succeed, you will be AUTHENTICATED (also <i>loadauth</i>).",

    "get":  "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Usage 1 : <i>get TERM</i>. Will display the entries matching TERM (searches in ID, title, login, url, and password fields.<br>" +
            "Usage 2 : <i>get TERM1 [TERM2 [TERM3 [...]]]</i>. Will display the entries matching <b>all</b> terms.<br>" +
            "Usage 3 : <i>get <b>-or</b> TERM [TERM2 [TERM3 [...]]]</i>. Will display the entries matching <b>any</b> of the terms.",

    "ls":   "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Equivalent of <i>get *</i>. Will display all entries.",

    "new":  "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Will create a new password entry. Fields to be filled : title, login, url, password.<br>" +
            "Will also try to <i>push</i> the changes to the server afterwards.",

    "gen":  "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Will create a new password entry, and generates a new password automatically for it. Fields to be filled : title, login, url.<br>" +
            "Will also try to <i>push</i> the changes to the server afterwards.",

    "edit": "Usage : <i>edit ID</i>. Will start an interactive process to edit the contents of an entry.<br>" +
            "IMPORTANT: by default, you need to fill the new fields again; the prompt is blank; use KEY_UP to redisplay the previous value of the field, and edit it.<br>" +
            "Will also try to <i>push</i> the changes to the server afterwards.",

    "rm":   "Usage : <i>rm ID</i>. Will start an interactive process to remove an entry.<br>" +
            "Will also try to <i>push</i> the changes to the server afterwards.",

    "rotate": "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Usage : <i>rotate ID</i>. Will generate a new random password for the entry ID.",

    "push": "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Will try to upload the current local content to the database, after encrypting it locally.<br>" +
            "Can fail if your push is <i>non-fast-forward</i>, i.e. the database version of the data is newer than yours.<br>" +
            "You can always <i>push --force</i> which ignores any verification, and overwrites the database content.",

    "pull": "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Will download the database content and replace local content with it, after decrypting it locally.<br>" +
            "Warning : you may lose local non-pushed data (push is automatic after any operation).",

    "clear": "Clears the screen.",

    "logout": "Remove in-memory login information (username, remote password, local password).<br>" +
            "After running <i>logout</i>, you will no longer be AUTHENTICATED.<br>" +
            "Does not deletes any cookie's login information.",

    "saveauth":  "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>).<br>" +
            "Usage: saveauth[ NUMBER=7], where NUMBER is the number of days to store the cookie.<br>" +
            "Saves the username, remote password in a cookie.<br>" +
            "You may use <i>loadauth</i> afterwards.",

    "loadauth":  "Prerequisite: you need to possess a cookie generated by <i>saveauth</i>.<br>" +
            "Tries to read the username, and remote password from the cookie Will prompt for the local password.<br>" +
            "If this command succeed, you will be AUTHENTICATED (also <i>loadauth</i>).",

    "clearauth":  "Removes vaultage's cookie.",

    "pwd":  "Prerequisite: you need to be AUTHENTICATED (see <i>auth</i>, <i>loadauth</i>).<br>" +
            "Will prompt to change local password.<br>" +
            "Will also try to <i>push</i> the changes to the server afterwards."
};